services:
  web:
   depends_on:
     - api
   build:
     context: ./spring-store-api
     dockerfile: Dockerfile
   image: spring-store-api:1.0
   ports:
     - 80:80
   restart: unless-stopped

  api:
    depends_on:
      - mysql
    build: ./spring-store-api
    image: spring-store-api:1.0
    ports:
      - 8080:8080
    environment:
      SERVER_ADDRESS: 0.0.0.0
      DB_URL: jdbc:mysql://mysql:3306/store_api?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: aB6fGk3nPW9XmQz1LpRt
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET_KEY: ${STRIPE_WEBHOOK_SECRET_KEY}
      SPRING_PROFILES_ACTIVE: dev
    command: ./docker-entrypoint.sh
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      DB_URL: jdbc:mysql://mysql:3306/store_api?createDatabaseIfNotExist=true
      DB_USERNAME: root
      MYSQL_ROOT_PASSWORD: aB6fGk3nPW9XmQz1LpRt
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
