spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242
swagger:
  server-url: http://localhost:8080